wandb_version: 1

model:
  desc: null
  value: meta-llama/Meta-Llama-3.1-8B
edenn_d:
  desc: null
  value: 2
edenn_n:
  desc: null
  value: 64
hadamard_groupsize:
  desc: null
  value: 1024
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.44.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723551716.0
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.14
      5: 0.16.4
      6: 4.44.0
      8:
      - 5
      13: linux-x86_64
