wandb_version: 1

model:
  desc: null
  value: meta-llama/Llama-2-7b-hf
dataset:
  desc: null
  value: red
seed:
  desc: null
  value: 0
nsamples:
  desc: null
  value: 256
percdamp:
  desc: null
  value: 0.1
nearest:
  desc: null
  value: false
wbits:
  desc: null
  value: 4
groupsize:
  desc: null
  value: 128
true_sequential:
  desc: null
  value: false
no_clip:
  desc: null
  value: false
skip_gq:
  desc: null
  value: false
save:
  desc: null
  value: ''
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710768651.0
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.16.4
      6: 4.36.2
      8:
      - 5
      13: linux-x86_64
